version: '3.5'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: stripe
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    environment:
#      SPRING_R2DBC_URL: r2dbc:postgresql://localhost:5432/stripe
#      SPRING_R2DBC_USERNAME: postgres
#      SPRING_R2DBC_PASSWORD: 123

volumes:
  postgres-data: